[pytest]
markers =
    env_o11: tests requiring o11 environment
    env_hebo: tests requiring hebo environment
    env_tidyhebo: tests requiring tidyhebo environment
    env_common: tests for whoch every environment should work
filterwarnings =
    ignore:The behavior of DataFrame concatenation:FutureWarning:hebo.optimizers.hebo
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::RuntimeWarning