task_name: colors_bob
less_is_better: true
on_simplex: true
params:
- name: red_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: orange_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: yellow_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: blue_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: green_aux
  type: continuous
  low: -2.0
  high: 2.0
y_p_star: 0.060390979051589966
y_p_w: 0.5460909008979797
