task_name: agnp
less_is_better: false
on_simplex: false
params:
- name: q_agno3
  type: continuous
  low: 4.53
  high: 42.80981595
- name: q_pva
  type: continuous
  low: 9.999518096000001
  high: 40.00101474
- name: q_tsc
  type: continuous
  low: 0.5
  high: 30.5
- name: q_seed
  type: continuous
  low: 0.498851653
  high: 19.5
- name: q_tot
  type: continuous
  low: 200.0
  high: 983.0
y_p_star: 1.392872536722466
y_p_w: 0.055425453541618465
