task_name: oer_plate_3496
less_is_better: true
on_simplex: true
params:
- name: ni_load_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: fe_load_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: co_load_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: mn_load_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: ce_load_aux
  type: continuous
  low: -2.0
  high: 2.0
- name: la_load_aux
  type: continuous
  low: -2.0
  high: 2.0
y_p_star: 0.3367150815743247
y_p_w: 0.6453159194452321
